import {defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  fields: [
    defineField({
      name: 'heroBuildWords',
      title: 'Hero: "We build ___" words',
      type: 'array',
      of: [{type: 'string'}],
      group: 'hero',
    }),
    defineField({
      name: 'heroForWords',
      title: 'Hero: "for ___" words',
      type: 'array',
      of: [{type: 'string'}],
      group: 'hero',
    }),
    defineField({
      name: 'aboutText',
      title: 'About Paragraph',
      description: 'Shown just below the hero, with a large drop-cap first letter',
      type: 'text',
      rows: 5,
      group: 'about',
    }),
    defineField({
      name: 'whyChooseUsEyebrow',
      title: 'Eyebrow label',
      description: 'e.g. "Why choose us"',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'whyChooseUsHeadingPrimary',
      title: 'Heading (dark part)',
      description: 'e.g. "We build for outcomes"',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'whyChooseUsHeadingSecondary',
      title: 'Heading (muted part)',
      description: 'e.g. "- not just launch day."',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'whyChooseUsDescription',
      title: 'Description',
      type: 'text',
      rows: 3,
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'statOneNumber',
      title: 'Stat 1: Number',
      description: 'e.g. "10+"',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'statOneLabel',
      title: 'Stat 1: Label',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'statOneDescription',
      title: 'Stat 1: Description',
      type: 'text',
      rows: 2,
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'statTwoNumber',
      title: 'Stat 2: Number',
      description: 'e.g. "100%"',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'statTwoLabel',
      title: 'Stat 2: Label',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'statTwoCaption',
      title: 'Stat 2: Caption next to avatars',
      description: 'e.g. "Direct to the founders"',
      type: 'string',
      group: 'whyChooseUs',
    }),
    defineField({
      name: 'servicesHeading',
      title: 'Services: Heading',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'servicesSubheading',
      title: 'Services: Subheading',
      type: 'string',
      group: 'services',
    }),
    defineField({
      name: 'philosophyPart1',
      title: 'Philosophy: Part 1 (plain)',
      type: 'string',
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyHighlight',
      title: 'Philosophy: Highlighted phrase',
      type: 'string',
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyPart2',
      title: 'Philosophy: Part 2 (plain)',
      type: 'string',
      group: 'philosophy',
    }),
    defineField({
      name: 'testimonialsHeading',
      title: 'Testimonials: Heading',
      type: 'string',
      group: 'testimonials',
    }),
    defineField({
      name: 'testimonialsSubheading',
      title: 'Testimonials: Subheading',
      type: 'string',
      group: 'testimonials',
    }),
    defineField({
      name: 'teamHeading',
      title: 'Team: Heading',
      type: 'string',
      group: 'team',
    }),
    defineField({
      name: 'teamSubheading',
      title: 'Team: Subheading',
      type: 'string',
      group: 'team',
    }),
    defineField({
      name: 'faqHeading',
      title: 'FAQ: Heading',
      type: 'string',
      group: 'faq',
    }),
    defineField({
      name: 'faqSubheading',
      title: 'FAQ: Subheading',
      type: 'string',
      group: 'faq',
    }),
    defineField({
      name: 'contactHeading',
      title: 'Contact: Heading',
      description: 'e.g. "Tell us what you\'re building."',
      type: 'string',
      group: 'contact',
    }),
  ],
  groups: [
    {name: 'hero', title: 'Hero'},
    {name: 'about', title: 'About'},
    {name: 'whyChooseUs', title: 'Why Choose Us'},
    {name: 'services', title: 'Services'},
    {name: 'philosophy', title: 'Philosophy'},
    {name: 'testimonials', title: 'Testimonials'},
    {name: 'team', title: 'Team'},
    {name: 'faq', title: 'FAQ'},
    {name: 'contact', title: 'Contact'},
  ],
  preview: {
    prepare() {
      return {title: 'Site Settings'}
    },
  },
})
